### PR TITLE
fix(UserCreation): adding new validation constraint in deserialization

### LINKED ISSUE #84: Validate the username before inserting
On peut créer un user juste avec des espaces

### PR DESCRIPTION
**Pull request by sguenier**

### CODE REVIEW

File: go/api/requests/user.go [hunk 1]
```diff
@@ -1,6 +1,6 @@
 package requests
 
 type UserCreateBody struct {
-	Username string `json:"username" binding:"required"`
-	Password string `json:"password" binding:"required" validate:"min=8,max=64"`
+	Username string `json:"username" binding:"required" validate:"not_trimmed_empty"`
+	Password string `json:"password" binding:"required" validate:"min=8,max=64,not_trimmed_empty"`
```
Comment (mrpinkcat) [inline go/api/requests/user.go]:
```suggestion
	Username string `json:"username" binding:"required" validate:"space_trimmed_empty"`
	Password string `json:"password" binding:"required" validate:"min=8,max=64,space_trimmed_empty"`
```

File: go/api/utils/deserializer.go [hunk 2]
```diff
@@ -23,10 +24,15 @@ func Deserialize(object any, context *gin.Context) (passed bool) {
 		return false
 	}
 	validate := validator.New()
+	_ = validate.RegisterValidation("not_trimmed_empty", SpaceTrimmedEmpty)
```
Comment (mrpinkcat) [inline go/api/utils/deserializer.go]:
```suggestion
	_ = validate.RegisterValidation("space_trimmed_empty", SpaceTrimmedEmpty)
```

**Review by mrpinkcat — CHANGES_REQUESTED** [review]

**Review by mrpinkcat — APPROVED** [review]
