### PR TITLE
fix(button): add icon + text on button + padding on bottom sheet buttons

### LINKED ISSUE #265: Repair Button

### PR DESCRIPTION
**Pull request by sguenier**

### CODE REVIEW

File: move_together_app/lib/Trip/trip_create_screen.dart [hunk 1]
```diff
@@ -121,11 +122,14 @@ class CreateTripScreenState extends State<CreateTripScreen> {
                                         dateTimeStart = selectedDateRange.start;
                                         dateTimeEnd = selectedDateRange.end;
                                         _dateController.text =
-                                            '${selectedDateRange.start.day}/${selectedDateRange.start.month} - ${selectedDateRange.end.day}/${selectedDateRange.end.month}';
+                                            '${DateFormat('dd/MM/yyyy').format(selectedDateRange.start)} - ${DateFormat('dd/MM/yyyy').format(selectedDateRange.start)}';
```
Comment (mrpinkcat) [inline move_together_app/lib/Trip/trip_create_screen.dart]: start -end

**Review by mrpinkcat — APPROVED** [review]
